### ISSUE TITLE
Serialization of attributes in Rails 6

### ISSUE THREAD

**Issue by johannaruiz** [jackc/tod#101]
In Rails 5.x serializtion of attributes had no issue

`serialize :time_open Tod::TimeOfDay`

When upgrading my app to Rails 6.1 the same serialization threw the following error:
`Cannot serialize Tod::TimeOfDay. Classes passed to serialize must have a 0 argument constructor.`

Is there a need to use something like active_model_serializers to serialize the attribute now or am I missing something?

**Comment by jackc** [comment]
I think you want to use the attribute method now. See the tests for an example:

https://github.com/jackc/tod/blob/9ac0e019a7d98171d80ca2aeb8e4e54e1048b418/test/tod/time_of_day_attribute_test.rb#L1-L16

**Comment by johannaruiz** [comment]
I don't know how I missed this! Thank you so much for pointing that out. Seriously, thank you 🙌
