### ISSUE TITLE
Query by TimeOfDay results in TypeError: Cannot visit Tod::TimeOfDay

### ISSUE THREAD

**Issue by dboyd68** [jackc/tod#28]
Hi,

Not sure if this should work. But query with Tod I get TypeError
e.g.

    Event.where(time_from: Tod::TimeOfDay.new(8, 30))

I get TypeError: Cannot visit Tod::TimeOfDay

where model is

    class Event < ActiveRecord::Base
    ...
    serialize :time_from, Tod::TimeOfDay
    ...

I expected this to work.
NOTE:

    Event.create(time_from: Tod::TimeOfDay.new(8, 30)) 

works fine.

**Comment by paultyng** [comment]
@dboyd68 see my patch in #29 

Not sure if it will be merged, Arel isn't my strong suit, but its what I was using locally.

**Comment by jackc** [comment]
I merged @paultyng's pull request. I'm not super into Arel either, but it passes the tests and doesn't change any public interfaces so it seems safe enough. I checked it on ActiveRecord 3.2, 4.0, 4.1, and 4.2 and it worked so it seems to be relying on something stable in Arel.
