### ISSUE TITLE
Can you explain?

### ISSUE THREAD

**Issue by jcdavison** [jackc/tod#30]
Hi @jackc 

Seems like a really useful gem, thanks.

I'm curious,

```
class Order < ActiveRecord::Base
  serialize :time, Tod::TimeOfDay
end
order = Order.create(time: Tod::TimeOfDay.new(9,30))
order.time                                      # => 09:30:00
```
indicates to me that the call to `.new(9,30)` is retrievable from the database when calling `.time()` and I would expect as you've documented to see `09:30:00` as the return value.  

I'm not quite getting that behavior and I don't see the method to 'reconstruct' the `Tod` object back to a string, which as one would imagine is quite necessary.

I've stored something using both the pattern

```
obj.attr == Tod::TimeOfDay.new(1,0)
```
&
```
obj.attr == Tod::TimeOfDay "1:00am"
```
Both of the above which appear to be storing something like, 
```
<Tod::TimeOfDay:0x007f94249c8190 @hour=1, @minute=0, @second=0, @second_of_day=3600>
```

In the database.  Interesting that no matter the write pattering being used, the return object checks true for equality.

```
obj.attr = Tod::TimeOfDay("1:00am")
=> #<Tod::TimeOfDay:0x007f9424c23598 @hour=1, @minute=0, @second=0, @second_of_day=3600>
```

What am I clearly  missing here?

Cheers,

JD

**Comment by paultyng** [comment]
This line:

```ruby
serialize :time, Tod::TimeOfDay
```

[Handles the serialization](http://apidock.com/rails/ActiveRecord/AttributeMethods/Serialization/ClassMethods/serialize) to and from the a database string field in to the `Tod::TimeOfDay` instance.  So the value in the database is just the string value (9:30:00, etc.).

The attribute is only operating on the `TimeOfDay` instance, never on a string.  That it outputs a string is just how the object is displayed in the console.

**Comment by jcdavison** [comment]
Perfect, and calling `.to_s` ironically I was missing that yesterday will return the underlying string value.  This is really useful gem btw, totally solved a huge amount of headache I was having with a calendaring system I'm working on.
