### ISSUE TITLE
shifts vs. ruby ranges

### ISSUE THREAD

**Issue by jjb** [jackc/tod#39]
I was pleased to find that `<=>` is defined, so ranges can be used

```
> morning = Tod::TimeOfDay.new(10)
> noon = Tod::TimeOfDay.new(12)
> afternoon = Tod::TimeOfDay.new(14)
> (morning..afternoon).cover? noon
=> true
```

What's the value of using `Tod::Shift` instead of ruby ranges?

**Comment by jjb** [comment]
maybe it's because ruby ranges don't support `overlaps?` like rails has?

```
> (morning..noon).overlaps?(noon..afternoon)
=> true
> (morning...noon).overlaps?(noon...afternoon)
=> false
```

**Comment by jackc** [comment]
Tod::Shift supports ranges that cross midnight. e.g. 9PM to 5AM. Ruby ranges do not support ranges where the the lower bound is actually higher than the upper bound.

So Tod::Shift can answer questions like: Does 9PM to 5AM include 1AM?

**Comment by jjb** [comment]
🆒
