### ISSUE TITLE
Tod Fails to Restore when loaded from active record when local time zone isn't DB time zone

### ISSUE THREAD

**Issue by rlugge** [jackc/tod#46]
If your database is stored in a different time zone (say, utc) than your default time zone (say, pacific), you run into issues when restoring models that have a stored TOD.  In my case, I build a time, store it into the database, and then get back a *different* time value than was stored.  If I generate a time with '8', plug it into the database, I get back a time with an hour part of 16 (4:00PM) when I reload the model.

Quick sketch of sample code below, with `BusinessHour` being a model with `start_time` as a time field in the DB, and set to serialize to TOD.  You can reproduce with a sample application by adding the following to the application.rb file:

```
config.time_zone='Pacific Time (US & Canada)'
config.active_record.default_timezone = :utc
```
I'd run this in the console, but you could add it to a spec:
```
bh = BusinessHour.new
start_time = Tod::TimeOfDay.new(12)
bh.start_time = start_time
bh.save
bh.reload
bh.start_time == start_time # returns false
start_time #<Tod::TimeOfDay:0x007fe88b6fef48 @hour=12, @minute=0, @second=0, @second_of_day=28800>
bh.start_time #<Tod::TimeOfDay:0x007fe88bd51cd8 @hour=20, @minute=0, @second=0, @second_of_day=72000>
```

My first thought, because the application I'm working on worked fine before we converted to explicitly storing data in UTC, was a time zone issue.   Everything worked fine when local time was the same as DB time, it only started breaking down when we had to explicitly lock DB time down to UTC to avoid timezone issues when importing data from the production server for testing.

**Comment by jackc** [comment]
What database column type is `start_time`?

**Comment by rlugge** [comment]
It's a time field.

**Comment by jackc** [comment]
It's working for me on Rails 4.2 and 5.0 on PostgreSQL. I don't have a 5.1 app handy but I suspect something changed where Time objects are automatically converted based on the Rails time zone. I seem to recall that Rails will load PostgreSQL `time` type into Ruby `Time` -- which doesn't really make sense because PG `time` doesn't have any date information.

**Comment by rlugge** [comment]
The sample app I have is Rails 5.1, PostgreSQL v 9.6.3

**Comment by jackc** [comment]
Okay, I spun up a Rails 5.1 app and was able to duplicate this behavior. It is as I suspected. For some reason Rails treats database `time` types as if time zones are meaningful. I have no idea where that would ever be useful or correct, but perhaps it makes sense in some context. Fortunately, it is easy to disable that behavior.

```
config.active_record.time_zone_aware_types = [:datetime]
```

I don't think this should have any adverse side effects, but I don't have any production 5.1 apps using Tod to test with.

Try with this config change and if everything works for you we can add this requirement to the documentation.

**Comment by rlugge** [comment]
Checking out master and trying out the tests there and it looks good.  Without the line, my unit tests blow up.  With the new config type, my unit tests pass.
