### ISSUE TITLE
Tod::TimeOfDay#to_formatted_s

### ISSUE THREAD

**Issue by tatey** [jackc/tod#49]
Hello,

Would you consider accepting a patch that implemented `#to_formatted_s` similar to `ActiveSupport::Time` and `ActiveSupport::Date`?

I have this monkey patch in my app.

``` ruby
if Tod::TimeOfDay.new(8).respond_to?(:to_formatted_s)
  raise "Tod::TimeOfDay monkey patch may be redundant. Check #{__FILE__}"
else
  module Tod
    class TimeOfDay
      TIME_FORMATS = {
        twelve_hour: -> (tod) { tod.min == 0 ? tod.strftime("%-l %P") : tod.strftime("%-l:%M %P") }
      }

      def to_formatted_s(format = :default)
        if formatter = TIME_FORMATS[format]
          if formatter.respond_to?(:call)
            formatter.call(self).to_s
          else
            strftime(formatter)
          end
        else
          to_s
        end
      end
    end
  end
end
```

My app is localized it would be great to be able to switch the format based on the current locale. I guess the biggest barrier to this enhancement would be agreeing on the formats? 

I'm happy to do the work if the maintainer is supportive.

**Comment by jackc** [comment]
I think this would be a good improvement.

> My app is localized it would be great to be able to switch the format based on the current locale.

I don't know what would be involved to do this but it'd be nice to have.

> I guess the biggest barrier to this enhancement would be agreeing on the formats?

Not sure what you mean here.
