### ISSUE TITLE
How to create a time in a specific timezone?

### ISSUE THREAD

**Issue by rlugge** [jackc/tod#56]
I strongly suspect that my issues arise out of a misunderstanding of how timezones work; if so, please feel free to point me in the direction of the necessary corrections.

My app is building timezones to determine if a given event occurs during specific business hours.  For what I hope are obvious reasons, we need to do this calculation in a timezone-aware manner.

I would have _expected_ the ToD gem to build that timezone based on the date I passed in.  If I pass in Time.zone.now, I'd expect the result to be build on the current zone.  Unfortunately, it appears that you just base it on the default time zone.

How do I create a time in a different time zone than the default zone, in a thread-safe manner so that multiple concurrent jobs won't stomp all over each other?

**Comment by jackc** [comment]
A time of day with a time zone would be incomplete unless it also had a date. Things like daylight savings time are impossible to determine correctly without it. But once you add a time zone and a date to a time of day you now have a normal datetime.

It sounds like the calculation / check you are trying to do needs to be done with actual datetimes. You can convert Tod::TimeOfDay objects to times with the `at` method. Tod::TimeOfDay#at will automatically use Time.zone if Rails time zone support is loaded and Rails Time.zone is thread safe.

**Comment by rlugge** [comment]
Oh, I get it.  That's why we use Time.zone.now instead of just Time.now normally -- it loads a TimeWithZone instead of just Time.  That was, we have the timezone information instead of the offset with the date and time.  And since you can't rely on people passing that data in, you have to use the system time.

Thank you for your time.
