### ISSUE TITLE
undefined method `register' for ActiveRecord::Type:Module

### ISSUE THREAD

**Issue by cbillen** [jackc/tod#61]
After updating to tod 2.2 in a Rails 4.2 environment/ruby 2.5

28: from bin/rails:4:in `<main>'
	27: from bin/rails:4:in `require'
	26: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	25: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	24: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:67:in `console'
	23: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	22: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
	21: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	20: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	19: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	18: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	17: from /Users/cbillen/Projects/heatwave/config/environment.rb:7:in `<top (required)>'
	16: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
	15: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
	14: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
	13: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
	12: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	11: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	10: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	 9: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
	 8: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
	 7: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 6: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 5: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 4: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	 3: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
	 2: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
	 1: from /Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/Users/cbillen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tod-2.2.0/lib/tod/railtie.rb:6:in `block in <class:Railtie>'

**Comment by jackc** [comment]
Yuck. Sometimes it's tricky to support two major versions of Rails at once. Just added a branch to split Rails 4 and 5 behavior. Try master and see if that works for you.

**Comment by kaligrafy** [comment]
now it says: LoadError: cannot load such file -- active_model/type

**Comment by jackc** [comment]
Hmm. I don't have a runnable 4.2.x Rails application to test with. So I'm kind of shooting blind here, but I just tried another thing on master.

**Comment by ssangervasi** [comment]
I have also been hit by this problem, and unfortunately my team is not able to upgrade past Rails 4.2.9 right now. 

The source of the issue seems to be that `Tod::Railtie` assumes Rails 4.x supports the `ActiveRecord::Type.register` interface [[source](https://github.com/jackc/tod/blob/14c54f00e056264379484d2d8f55568e327a3b74/lib/tod/railtie.rb#L12)].

However, the Rails 4 equivalent is `ActiveRecord ::Type::TypeMap#register_type` [[source](https://github.com/rails/rails/blob/v4.2.11/activerecord/lib/active_record/type/type_map.rb#L23)]. As far as I can tell, this API is undocumented (perhaps meant to be private/experiment).

In my project, I actually don't need the Record/Models integration at all -- I just want to load Tod in a Rails app without errors. I would accept either a `#register_type` compatibility fix or a non-hack way of disabling this integration.

**Comment by jackc** [comment]
If you don't need Rails integration, then you might be able to get by doing `require: false` in your `Gemfile` and manually requiring the parts you need.

Instead of:

```ruby
require 'tod'
```

Try this:

```ruby
require 'tod/time_of_day'
require 'tod/shift'
require 'tod/conversions'
```

**Comment by ssangervasi** [comment]
That's good to know, but unfortunately tod is required by a dependency which itself is doing the full require. I have a hacky solution which involves making my own railtie initializer that checks for compatibility and modifies tod if necessary. But it's rather gross.

**Comment by ssangervasi** [comment]
I would be happy to work on a Rails 4.2.x compatibility patch. What behavior is best?

1. Detect the missing feature, and log a warning, and do nothing in the railtie.
2. Allow the railtie integration to be disabled through a Rails configuration setting.
3. Implement the type using `ActiveRecord::Type::TypeMap#register_type`, if possible.

**Comment by jackc** [comment]
I suppose 3 is best if if it can be done easily.

**Comment by RonGans** [comment]
was this ever resolved?

**Comment by ssangervasi** [comment]
@RonGans - No, I was able to upgrade to Rails 5 around the time 4 stopped being supported. Here's the hack I used to remove the issue during the transition:
```rb
# config/initializers/tod_compatability.rb
require 'tod/railtie'

module TodCompatability
  class Railtie < Rails::Railtie
    BROKEN_INITIALIZER_NAME = 'tod.register_active_record_type'

    initializer(
      'tod_compatability.check_register_active_record',
      before: BROKEN_INITIALIZER_NAME
    ) do |app|
      tod_railtie = app.railties.find do |railtie|
        railtie.is_a?(Tod::Railtie)
      end

      break if tod_railtie.blank?

      Rails.logger.warn(
        <<~WARNING_MESSAGE
          Tod::Railtie intitializer #{BROKEN_INITIALIZER_NAME} is disabled
          due to an incompatability with Rails 4.x.
          See: https://github.com/jackc/tod/issues/61
        WARNING_MESSAGE
      )

      broken_initalizer =
        tod_railtie
        .initializers
        .find { |initializer| initializer.name == BROKEN_INITIALIZER_NAME }

      if broken_initalizer.blank?
        Rail.logger.warn(
          <<~WARNING_MESSAGE
            Tod::Railtie intitializer #{BROKEN_INITIALIZER_NAME} is not defined.
            This may mean the issue was resolved and that this code can be removed.
          WARNING_MESSAGE
        )
        break
      end

      noop = proc {}
      broken_initalizer.instance_variable_set(:@block, noop)
    end
  end
end
```

**Comment by jackc** [comment]
Latest version of tod drops support for Rails 4 so I'm going to close this.
