### ISSUE TITLE
undefined method `type' for Tod::TimeOfDay:Class

### ISSUE THREAD

**Issue by julitrows** [jackc/tod#84]
Hello, thanks for ToD!

I was upgrading to 3.0 from the prior version, just before trying to upgrade my app to Rails 6.1, so here's the stack:

- Ruby 2.7.2
- Rails 6.0.4
- ToD 3.0

```rb
class AssignmentSchedule::DaySegment < ApplicationRecord
  attribute :starts_at, Tod::TimeOfDay
  attribute :ends_at, Tod::TimeOfDay
  attribute :accept_time, Tod::TimeOfDay
  attribute :respond_time, Tod::TimeOfDay
  # ...
end
```

All these fields used to be `serialize`, but I was getting errors around the expected arguments of the TOD `initialize` method, so, after reading some issues in this repo, I changed it for `attribute`.

But now, when I try to run my rspec suite in CI I get this error:

```rb
NoMethodError: undefined method `type' for Tod::TimeOfDay:Class
bundle/ruby/2.7.0/gems/activerecord-6.0.4/lib/active_record/attribute_methods/time_zone_conversion.rb:84:in `create_time_zone_conversion_attribute?'
bundle/ruby/2.7.0/gems/activerecord-6.0.4/lib/active_record/attribute_methods/time_zone_conversion.rb:73:in `block (2 levels) in inherited'
```

Locally, I'm using the `dead_end` gem which provides some more context info:

```rb
NoMethodError:
  undefined method `type' for Tod::TimeOfDay:Class

     3  module ActiveRecord
     4    module AttributeMethods
     5      module TimeZoneConversion
    64        module ClassMethods # :nodoc:
    65          private
    80            def create_time_zone_conversion_attribute?(name, cast_type)
    81              enabled_for_column = time_zone_aware_attributes &&
  ❯ 84              enabled_for_column && time_zone_aware_types.include?(cast_type.type)
    85            end
    86        end
    87      end
    88    end
    89  end
```

Looking at AR's code, the default set for `time_zone_aware_types` is `%i[datetime time]`([here](https://github.com/rails/rails/blob/v6.0.4/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb#L61))

The cast type here would be `Tod::TimeOfDay`, as second argument to the `attribute` declaration

Seems this class needs to define a `type` method or attribute that returns something that can be reconciled with the `time_zone_aware_types` config?

In my app, I have it as `%i[datetime]` as defined in the application as per this config line in `application.rb`:

```rb
config.active_record.time_zone_aware_types = [:datetime]
```

Other options:

1. Some more info needs to be passed into the declaration of my attributes? Using `options` [maybe](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html)?
2. Do I need to register a custom type?

Any help or guidance to determine this will be appreciated!

Thanks a lot!

**Comment by jackc** [comment]
Yes, the type needs to be registered. I have it in the tests, but neglected to add it to the docs.

Here's example usage:

```
ActiveModel::Type.register(:time_only, Tod::TimeOfDayType)
ActiveRecord::Type.register(:time_only, Tod::TimeOfDayType)

class Order < ActiveRecord::Base
  attribute :time, :time_only
end
```

**Comment by julitrows** [comment]
Thanks for the super-fast response. This works!

If you don't mind, I'll be opening a PR with a section on the readme about this.

Cheers!

**Comment by julitrows** [comment]
Oh well, I see you already did add it to the `master`. Thanks again.

I'll be closing this issue then!

Cheers!
