### ISSUE TITLE
Serialization does not work with Rails 6.1

### ISSUE THREAD

**Issue by rakibulislam** [jackc/tod#85]
Hi There,

I have a Rails 6.0.4 app where I have been using TOD without any issues. But, when I am doing a Rails upgrade to 6.1.4, I found that the serialization does not work anymore. Here is my model file:

```ruby
class Shift < ApplicationRecord
  serialize :start_time, Tod::TimeOfDay
  serialize :end_time, Tod::TimeOfDay
end
```

In Rails 6.0.4, I am getting expected results:
```ruby
> Shift.last.start_time
=> #<Tod::TimeOfDay:0x00007f81aaf8e408 @hour=0, @minute=0, @second=0, @second_of_day=0>
> Shift.last.end_time
=> #<Tod::TimeOfDay:0x00007f81aabb4378 @hour=5, @minute=0, @second=0, @second_of_day=18000>
```

But, in Rails 6.1.4, I am getting nil values for the TOD fields:
```ruby
> Shift.last.start_time
=> nil
> Shift.last.end_time
=> nil
```

Is it a known issue? Or, am I missing something?

Best,
Rakib

**Comment by jackc** [comment]
Some things have changed with Rails. Use `attribute` instead of `serialize`. See https://github.com/jackc/tod#activerecord-attribute-support.

**Comment by rakibulislam** [comment]
That fixes the issue. Thanks so much for the quick reply @jackc 💯
